const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2022 - 2023",
    title: "SheCodes React Web Development",
    institution: "SheCodes",
    desc: "Online Coding Workshops for Women",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2022",
    title: "EF set English Certificate C1 advanced",
    institution: "EF - Education First Italia",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2015 - 2018",
    title: "Master's Degree in Specialized Translation",
    institution: "University of Bari Aldo Moro",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2011 - 2015",
    title:
      "Bachelor's degree in Language and Intercultural Mediation, Linguistic and Intercultural Communication",
    institution: "University of Bari Aldo Moro",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2021",
    title: "Consecutive interpreter",
    institution: "Fincantieri",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2017 - 2020",
    title: "Translator",
    institution: "SJS Engineering srl",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2009 - 2013",
    title: "Transcriber",
    institution: "Alchemy Translations",
  },
  {
    id: 8,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019",
    title: "Audiovisual Translator",
    institution: "10D Film",
  },
];
export default Data;
